- hosts: myserver
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'
      tags: [always]

    - name: Install necessary packages for Python and virtual environments
      apt:
        name: 
          - python3
          - python3-pip
          - python3-venv
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-dev
        state: present
      tags: [python, setup]

    - name: Create directories
      file:
        path: "/home/alaingcp2023_gmail_com/{{ item }}"
        state: directory
      loop:
        - project/src
        - utils

    - name: Setup a Python virtual environment in 'evm' directory
      command: python3 -m venv /home/alaingcp2023_gmail_com/evm
      args:
        creates: /home/alaingcp2023_gmail_com/evm/bin/activate
      tags: [python, venv]

    - name: Copy requirements.txt to the remote machine
      copy:
        src: requirements.txt
        dest: /home/alaingcp2023_gmail_com/requirements.txt
      tags: [python, venv]

    - name: Install Python packages within the virtual environment from requirements.txt
      pip:
        requirements: /home/alaingcp2023_gmail_com/requirements.txt
        virtualenv: /home/alaingcp2023_gmail_com/evm
        virtualenv_command: python3 -m venv
      tags: [python, venv]
