- hosts: myserver
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'
      tags: [always]

    - name: Install necessary packages for Python and virtual environments
      apt:
        name: 
          - python3
          - python3-pip
          - python3-venv
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-dev
        state: present
      tags: [python, setup]

    - name: Create directories
      file:
        path: "/home/alainahebie_gmail_com/{{ item }}"
        state: directory
      loop:
        - project/compute-instances/src
        - project/compute-instances/logs
        - project/compute-instances/files
        - project/compute-instances/test
        - utils

    - name: Grant full permissions to 'alainahebie_gmail_com' for the 'project' directory and all within
      file:
        path: "/home/alainahebie_gmail_com/project"
        owner: alainahebie_gmail_com
        group: alainahebie_gmail_com
        mode: '0775'
        recurse: yes
        state: directory

    - name: Copy main.py to the remote machine
      copy:
        src: /mnt/c/Users/AHEBIE/Documents/GHUB/ethereum-airflow/compute-instances/main.py
        dest: /home/alainahebie_gmail_com/project/compute-instances/main.py
      tags: [deploy, compute-instances]

    - name: Copy ethereum_data_collector.py to the remote machine
      copy:
        src: /mnt/c/Users/AHEBIE/Documents/GHUB/ethereum-airflow/compute-instances/src/ethereum_data_collector.py
        dest: /home/alainahebie_gmail_com/project/compute-instances/src/ethereum_data_collector.py
      tags: [deploy, compute-instances]

    - name: Setup a Python virtual environment in 'evm' directory
      command: python3 -m venv /home/alainahebie_gmail_com/evm
      args:
        creates: /home/alainahebie_gmail_com/evm/bin/activate
      tags: [python, venv]

    - name: Copy requirements.txt to the remote machine
      copy:
        src: /mnt/c/Users/AHEBIE/Documents/GHUB/ethereum-airflow/requirements.txt
        dest: /home/alainahebie_gmail_com/requirements.txt
      tags: [python, venv]

    - name: Install Python packages within the virtual environment from requirements.txt
      pip:
        requirements: /home/alainahebie_gmail_com/requirements.txt
        virtualenv: /home/alainahebie_gmail_com/evm
        virtualenv_command: python3 -m venv
      tags: [python, venv]
